version: '3'
services:
  builder:
    container_name: drone-provider-builder
    hostname: drone-provider-builder
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command:
    - sh
    - "-c"
    - "go get -v && go build -v ."
    restart: "no"
    volumes:
    - ..:/go/src/github.com/artisanofcode/terraform-provider-drone
